- name: Create dave user
  ansible.builtin.user:
    name: dave
    password: '{{ (user_dave_password | string | ansible.builtin.password_hash("sha512", 65534 | random(seed=inventory_hostname) | string)) if user_dave_password is defined else "" }}'
    comment: Dave James Miller
    groups: [adm, sudo, www-data]
    append: true
    shell: /bin/bash
  register: user_dave

- name: Copy SSH key
  ansible.posix.authorized_key:
    user: dave
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGRzRUvx7ESGxsXrmNKgVY+pg8uc1ZHxzqVoMVznlzWF d@djm.me
    exclusive: true

- ansible.builtin.import_role:
    name: helper_dotfiles
  become: true
  become_user: dave

- name: Create ~/.marks directory
  ansible.builtin.file:
    path: ~dave/.marks
    state: directory
    owner: dave
    group: dave
