- name: Create dave user
  ansible.builtin.user:
    name: dave
    password: '{{ tofu_outputs[ansible_hostname + "_dave_password"].value | password_hash("sha512", 65534 | random(seed=inventory_hostname) | string) }}'
    comment: Dave James Miller
    groups: [adm, sudo, www-data]
    append: true
    shell: /bin/bash

- name: Copy SSH key
  ansible.posix.authorized_key:
    user: dave
    state: present
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGRzRUvx7ESGxsXrmNKgVY+pg8uc1ZHxzqVoMVznlzWF d@djm.me
