- name: Clone Uptime Kuma configuration repository
  ansible.builtin.git:
    repo: https://github.com/d13r/kuma.git
    dest: /local/kuma
    update: false
  become: true
  become_user: dave

- name: Start Uptime Kuma
  community.docker.docker_compose_v2:
    project_src: /local/kuma

- name: Enable Apache HTTP proxy
  community.general.apache2_module:
    name: proxy_http
    state: present
  notify: Reload Apache

- name: Configure the kuma.{{ base_hostname }} vhost
  ansible.builtin.template:
    src: kuma-site.conf.j2
    dest: /etc/apache2/sites-enabled/kuma.conf
  notify: Reload Apache
