- name: Clone Collector repository
  ansible.builtin.git:
    repo: https://github.com/d13r/collector.git
    dest: /local/collector
    update: false
  become: true
  become_user: dave

- name: Configure Collector
  ansible.builtin.template:
    src: config.php.j2
    dest: /local/collector/config.php
    group: www-data
    mode: '0660'
  vars:
    password_hash: '{{ collector_password_hash }}'

- name: Install Collector dependencies
  ansible.builtin.command: composer install --no-interaction --no-dev
  args:
    chdir: /local/collector
    creates: /local/collector/vendor
  become: true
  become_user: dave

- name: Configure the c.{{ base_hostname }} vhost
  ansible.builtin.template:
    src: collector-site.conf.j2
    dest: /etc/apache2/sites-enabled/collector.conf
  notify: Reload Apache
