- name: Create symlink to Desktop
  ansible.builtin.shell: |
    winpath=$(powershell.exe -Command "[Environment]::GetFolderPath('Desktop')" | tr -d '\r')
    ln -nsfv "$(wslpath "$winpath")" ~/Desktop
  args:
    creates: ~/Desktop

- name: Create symlink to Documents
  ansible.builtin.shell: |
    winpath=$(powershell.exe -Command "[Environment]::GetFolderPath('MyDocuments')" | tr -d '\r')
    ln -nsfv "$(wslpath "$winpath")" ~/Documents
  args:
    creates: ~/Documents

- name: Create symlink to Dropbox
  ansible.builtin.shell: |
    winpath=$(powershell.exe -Command 'gc $env:localappdata\Dropbox\host.db | select -index 1' | base64 -di)
    ln -nsfv "$(wslpath "$winpath")" ~/Dropbox
  args:
    creates: ~/Dropbox
