- name: Install Certbot
  ansible.builtin.apt:
    name:
      - certbot
      - python3-certbot-apache
      - python3-certbot-dns-cloudflare

- name: Configure Certbot Cloudflare credentials
  ansible.builtin.template:
    src: cloudflare-credentials.ini.j2
    dest: /etc/letsencrypt/cloudflare-credentials.ini
    mode: '0600'
  vars:
    token: '{{ tofu_outputs[ansible_hostname + "_cloudflare_certbot_token"].value }}'

- name: Generate default certificate
  ansible.builtin.shell: |
    sudo certbot certonly \
      --non-interactive \
      --cert-name default \
      --domains '{{ certbot_default_domains | join(',') }}' \
      --dns-cloudflare \
      --dns-cloudflare-credentials /etc/letsencrypt/cloudflare-credentials.ini \
      --dns-cloudflare-propagation-seconds 30 \
      --email d@djm.me \
      --agree-tos
  args:
    creates: /etc/letsencrypt/live/default

- name: Create Certbot renewal hooks directory
  ansible.builtin.file:
    # This isn't created until the first certificate has been issued
    path: /etc/letsencrypt/renewal-hooks/deploy
    state: directory

- name: Create renewal script
  ansible.builtin.copy:
    src: deploy.sh
    dest: /etc/letsencrypt/renewal-hooks/deploy/deploy.sh
