- name: Provision Artemis (Hetzner VM)
  hosts: artemis

  roles:
    - role: user_root
    - role: user_dave
    - role: action_apt_update
    - role: config_hostname
    - role: config_sudo
    - role: config_swapfile
    - role: config_timezone
    - role: config_unattended_upgrades
    - role: software_fail2ban
    - role: software_lazygit
    - role: software_postfix
    - role: software_utilities
    - role: project_collector
    - role: project_davejamesmiller_com
    - role: project_djm_me
    - role: project_kuma
