# From Ubuntu 25.10:
# - name: Install Lazygit
#   ansible.builtin.apt:
#     name: lazygit
#     state: present

- name: Install Lazygit
  ansible.builtin.shell: |
    cd /tmp

    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | \grep -Po '"tag_name": *"v\K[^"]*')
    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/download/v${LAZYGIT_VERSION}/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
    tar xf lazygit.tar.gz lazygit
    sudo install lazygit -D -t /usr/local/bin/

    rm -f lazygit.tar.gz lazygit
  args:
    creates: /usr/local/bin/lazygit
