- name: Create temp directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: adm
    mode: g+ws
    recurse: true
  loop:
    - /local/temp
    - /local/temp/public

- name: Copy phpinfo.php
  ansible.builtin.copy:
    src: phpinfo.php
    dest: /local/temp/public/phpinfo.php

- name: Configure the temp.{{ base_hostname }} vhost
  ansible.builtin.template:
    src: temp-site.conf.j2
    dest: /etc/apache2/sites-enabled/temp.conf
  notify: Reload Apache
